backend/build.gradle
backend/src/main/java/com/umc/mwomeokji/domain/user/api/UserController.java
backend/src/main/java/com/umc/mwomeokji/domain/user/application/UserServiceImpl.java
backend/src/main/java/com/umc/mwomeokji/domain/user/dao/UserRepository.java
backend/src/main/java/com/umc/mwomeokji/domain/user/dto/UserDto.java
backend/src/main/java/com/umc/mwomeokji/domain/user/exception/DuplicateEmailException.java
backend/src/main/java/com/umc/mwomeokji/global/error/ExceptionResponse.java
backend/src/main/java/com/umc/mwomeokji/global/error/GlobalExceptionHandler.java
backend/src/main/java/com/umc/mwomeokji/global/error/exception/BusinessException.java
backend/src/main/java/com/umc/mwomeokji/global/error/exception/ExceptionCodeAndDetails.java

- 백엔드 전역 예외처리 클래스, 비즈니스 예외 처리 클래스 구성
- resolved: #3 
<br>
- Controller 입력으로 들어오는 Request 에 대한 binding error 발생 시 예외 처리 수행
- 지원하지 않는 HTTP method 호출 시 예외 처리 수행
- 지정한 businessException 발생 시 예외 처리 수행
- 기타 직접 handling 하지 않는 예외에 대한 예외 처리 수행
<br>
- x
<br>
- 코드 하나하나 살펴보고 조금이라도 모르는 곳 있거나, 수정해야 하거나 더 좋은 방향 있다면 꼭 리뷰 남겨주기!

feat: 전역 예외 클래스, 비즈니스 예외 클래스 구성

---

backend/src/main/java/com/umc/mwomeokji/domain/dish/api/DishController.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/application/DishService.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/application/DishServiceImpl.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dao/DishRepository.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/domain/Dish.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dto/DishDto.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dto/DishMapper.java
backend/src/main/java/com/umc/mwomeokji/domain/question/api/QuestionController.java
backend/src/main/java/com/umc/mwomeokji/domain/question/application/QuestionService.java
backend/src/main/java/com/umc/mwomeokji/domain/question/application/QuestionServiceImpl.java
backend/src/main/java/com/umc/mwomeokji/domain/question/dao/QuestionRepository.java
backend/src/main/java/com/umc/mwomeokji/domain/question/domain/Question.java
backend/src/main/java/com/umc/mwomeokji/domain/question/dto/QuestionDto.java
backend/src/main/java/com/umc/mwomeokji/domain/question/dto/QuestionMapper.java

- 프론트엔드 요청/응답 테스트를 위한 비즈니스 로직 없는 mock API 작성
- resolved: #6 
<br>
- dish, question 도메인 프로젝트 스켈레톤 생성
- 비즈니스 로직 없이 하드코딩 통하여 Controller 에서 값 직접 반환하도록 작성
<br>
- 없음
<br>
- 없음

feat: dish, question 도메인 mock API 작성

---

backend/src/main/java/com/umc/mwomeokji/domain/question/api/QuestionController.java
backend/src/main/java/com/umc/mwomeokji/domain/question/application/QuestionServiceImpl.java
backend/src/main/java/com/umc/mwomeokji/domain/question/domain/Question.java
backend/src/main/java/com/umc/mwomeokji/domain/question/dto/QuestionDto.java

- question 도메인 연관관계 매핑
<br>
- question 도메인 연관관계 매핑
<br>
- 다대일 관계 조사 후 코드 수정 필요, 아직 미완성 상태
<br>
-

feat: question 도메인 연관관계 매핑

---

backend/src/main/java/com/umc/mwomeokji/domain/dish/api/DishController.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/application/DishService.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/application/DishServiceImpl.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dto/DishDto.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dto/DishMapper.java
backend/src/main/java/com/umc/mwomeokji/domain/question/api/QuestionController.java
backend/src/main/java/com/umc/mwomeokji/domain/question/application/QuestionService.java
backend/src/main/java/com/umc/mwomeokji/domain/question/application/QuestionServiceImpl.java
backend/src/main/java/com/umc/mwomeokji/domain/question/domain/Question.java
backend/src/main/java/com/umc/mwomeokji/domain/question/domain/QuestionDish.java
backend/src/main/java/com/umc/mwomeokji/domain/question/dto/QuestionDto.java
backend/src/main/java/com/umc/mwomeokji/domain/question/dto/QuestionMapper.java
backend/src/test/java/com/umc/mwomeokji/domain/dish/api/DishControllerTest.java
backend/src/test/java/com/umc/mwomeokji/domain/dish/application/DishServiceImplTest.java

- dishesNameResponse 를 dishNameResponse 로 수정
<br>
- dishesNameResponse 를 dishNameResponse 로 수정
<br>
- x
<br>
- x

style: dishesNameResponse 를 dishNameResponse 로 수정

---

backend/src/main/java/com/umc/mwomeokji/DataLoader.java
backend/src/main/java/com/umc/mwomeokji/domain/QuestionDish/dao/dto/QuestionDishDto.java
backend/src/main/java/com/umc/mwomeokji/domain/QuestionDish/dao/dto/QuestionDishMapper.java
backend/src/test/java/com/umc/mwomeokji/acceptance/question/QuestionAcceptanceTest.java
backend/src/test/java/com/umc/mwomeokji/acceptance/question/QuestionAcceptanceTestTool.java
backend/src/test/java/com/umc/mwomeokji/domain/question/api/QuestionControllerTest.java
backend/src/test/java/com/umc/mwomeokji/domain/question/application/QuestionServiceImplTest.java

- 작업 내용을 적어주세요.
- resolved: #17 
<br>
- 주요 변경사항에 대해 적어주세요.
<br>
- 팀원이 유의해야할 변경 사항이나 로직이 생겼다면 적어주세요.
<br>
- 리뷰어에게 부탁할 내용(ex.~부분 도움 부탁합니다, ~부분 한 번 더 검토 부탁드려요) 이 있다면 적어주세요.

question 테스트 코드 작성

---

backend/build.gradle
backend/src/main/java/com/umc/mwomeokji/domain/dish/api/DishController.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/application/DishService.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/application/DishServiceImpl.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dto/DishDto.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dto/DishMapper.java
backend/src/main/java/com/umc/mwomeokji/global/config/JpaAuditingConfig.java
backend/src/main/java/com/umc/mwomeokji/global/config/WebMvcConfig.java
backend/src/main/java/com/umc/mwomeokji/global/error/exception/ExceptionCodeAndDetails.java
backend/src/main/java/com/umc/mwomeokji/infra/s3/AwsS3Config.java
backend/src/main/java/com/umc/mwomeokji/infra/s3/FileService.java
backend/src/main/java/com/umc/mwomeokji/infra/s3/FileServiceImpl.java
backend/src/main/resources/application-local.yml
backend/src/main/resources/application.yml

- 새로운 메뉴 저장 API 작성
- AWS S3 연동
- Spring boot 포트번호 변경, CORS 이슈 해결
- resolved: #10 
- resolved: #33 
- resolved: #52 
<br>
- 새로운 메뉴를 저장하기 위한 API 작성
- AWS S3 연동, 메뉴 저장 API 에 이미지를 함께 첨부할 시 S3 에 이미지를 저장한 후 파일 이름을 반환하도록 작성
- Spring boot 포트번호를 변경하고 client 에 대한 CORS 이슈를 해결
- spring cloud starter aws 의존성을 통해 AmazonS3 클라이언트를 자동으로 생성하고자 하였으나, 프로젝트 실행시간이 지나치게 길어지는 탓에 aws java sdk bom 으로 의존성을 교체한 후 AmazonS3 클라이언트 직접 생성 방식으로 변경
<br>
- x
<br>
- x

feat: 메뉴 저장 API 작성, S3 연동, fix: CORS 이슈 해결

---

backend/src/main/java/com/umc/mwomeokji/DataLoader.java

- 더미 데이터 질문, 메뉴 추가
- <br>
- 더미데이터가 추가
<br>
- x
<br>
- x

chore: 더미 데이터 질문, 메뉴 추가

---

backend/src/main/java/com/umc/mwomeokji/DataLoader.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/api/DishController.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/application/DishService.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/application/DishServiceImpl.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dao/DishRepository.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dto/DishDto.java
backend/src/main/java/com/umc/mwomeokji/domain/dish/dto/DishMapper.java
backend/src/main/java/com/umc/mwomeokji/global/error/GlobalExceptionHandler.java
backend/src/main/java/com/umc/mwomeokji/global/error/exception/ExceptionCodeAndDetails.java

- 메뉴의 총 개수 조회 API 작성
- 메뉴 이름을 통한 메뉴 상세 정보 조회 API 작성
- resolved: #62 
- resolved: #59 
<br>
- 더미데이터 메뉴 이름 소수 변경
- 예외 메시지 소수 변경
- BindException 예외 처리 클래스 추가
- 메뉴의 총 개수 조회 API, 메뉴 이름을 통한 메뉴 상세 정보 조회 API 작성
<br>
- x
<br>
- x
<br>

feat: 메뉴의 총 개수 조회, 이름을 통한 상세 정보 조회 API 작성

---

frontend/front_head/index.html
frontend/front_head/nav.html
frontend/front_head/style.css

드롭다운메뉴 css 수정했습니다.
- resolved: #74
<br>
드롭다운메뉴 css 수정
이미지 경로도 변경했습니다.
<br>
- 추후에 index.html 삭제합니다.

fix: navbar 드롭다운메뉴 수정

---

frontend/front_head/nav.html
frontend/front_head/style.css

- navbar 드롭다운메뉴 내용 수정
- resolved: #79
<br>
- navbar 드롭다운메뉴 내용 수정 : 소개 / 뭐 먹지? / 고객센터 --> 소개 / 뭐 먹지? / 나의 그릇
- hr css도 변경했습니다.
<br>

fix: navbar 내용 수정

---

.gitignore
backend/.gitignore
backend/build.gradle
backend/src/main/resources/application.yml

- AWS RDS 연결 및 운영 환경 설정을 위한 application-prod.yml 작성
- resolved: #34
<br>
- application-prod.yml 파일 추가
- build.gradle 에 mariadb 의존성 추가
<br>
- application-prod.yml 은 RDS 의 민감정보가 들어있기 때문에 외부로 노출되면 안 됨
- .gitignore 에 등록해두었음
<br>
- x
<br>

feat: AWS RDS 연결 및 운영 환경 설정을 위한 application-prod.yml 작성

---

frontend/front_main/main_main_sec.css

- main nav적용 안되던 것 수정
<br>
- background-color 삭제
<br>
- merge 후 확인 한번만 해주세요

edit: main file

---

backend/src/main/java/com/umc/mwomeokji/global/error/GlobalExceptionHandler.java
backend/src/main/java/com/umc/mwomeokji/global/error/exception/ExceptionCodeAndDetails.java

- 파일 업로드 사이즈 초과에 대한 예외 처리
- resolved: #96 
<br>
- 전역 예외 처리 클래스에 업로드 사이즈 예외에 대한 예외 핸들러 메소드 추가 작성
<br>
- x
<br>
- x
<br>

feat: 파일 업로드 사이즈 초과에 대한 예외 처리

---

frontend/front_twenty/twenty_loading.css
frontend/front_twenty/twenty_loading.js

- loading페이지 이미지 위치와 guess페이지 사진을 바꿈
- resolved:
<br>
- 이미지 교체와 이미지 위치 조정
<br>
- 테스트 부탁드립니다. 그리고 아까 문제 해결하면서 바로 merge되서 다시 pr보내요 또 문제 있으면 바로 고치겠습니다.

feat:loading page 수정

---

.github/workflows/backend-build.yml
.github/workflows/backend-develop-test.yml

- GitHub Actions default working-directory 수정
- resolved: #36 
- resolved: #104 
<br>
- GitHub Actions default working-directory 수정
<br>
- develop 브랜치의 backend 파일로의 PR 이 발생하면 자동으로 테스트코드가 수행되며, 수행 결과를 알려준다.
- develop / main 브랜치의 backend 파일로의 push 가 발생하면 자동으로 테스트, 빌드가 수행되며, 수행 결과를 알려준다.
<br>
- x
<br>

feat: GitHub Actions 에서 빌드한 Jar 파일을 AWS S3 로 전송

---

.github/workflows/backend-build.yml
backend/appspec.yml
backend/scripts/deploy.sh
backend/src/main/resources/application-local.yml

- CodeDeploy 배포 자동화 구성 완료
- resolved: #103 
- resolved: #119 
<br>
- GitHub Actions 를 통해 AWS S3 bucket 에 저장한 zip 파일을 AWS CodeDeploy 를 이용하여 EC2 서버에 배포
- 이 때 zip 파일에는 배포에 필요한 배포 쉘 스크립트, appspec.yml, 빌드한 jar 파일 3개를 포함
- CodeDeploy 에서는 배포를 위한 쉘 스크립트인 deploy.sh 를 실행하여 배포 수행
<br>
- x
<br>
- x
<br>

feat: CodeDeploy 배포 자동화 구성 완료

---

backend/appspec.yml
backend/build.gradle
backend/scripts/find_port.sh
backend/scripts/health.sh
backend/scripts/start.sh
backend/scripts/stop.sh
backend/scripts/switch.sh
backend/src/main/java/com/umc/mwomeokji/HealthController.java
backend/src/main/resources/application-local.yml

- CodeDeploy hook 수명 주기에 따른 스크립트 작성
- 빌드 시간에 따라 버전이 추가되도록 수정
- NGINX 를 이용한 무중단 배포 환경 구성
- resolved: #37 
<br>
- CodeDeploy 의 수명주기에 따라 배포 시작 시 휴식 중인 포트를 찾아 구동 중인 프로세스를 종료
- 해당 포트에 새롭게 배포된 java 애플리케이션을 실행
- NGINX 포트 변경 후 정상적으로 서버가 구동 중인지 health check 진행
<br>
- x
<br>
- x
<br>

feat: 무중단 배포를 위한 CodeDeploy 설정, 자동화 관련 배포 스크립트 작성

---

backend/build.gradle
backend/scripts/find_port.sh
backend/scripts/health.sh
backend/scripts/stop.sh

- build 파일에 대한 타임 존을 한국으로 설정
- 기타 오타 수정
- resolved: #123 
<br>
- build 파일에 대한 타임 존을 한국으로 설정
<br>
- x
<br>
- x
<br>

fix: timezone 설정, 기타 오타 수정

---

frontend/front_rps/rps_input.css
frontend/front_rps/rps_input.html
frontend/front_rps/rps_input.js
frontend/front_rps/rps_loading.css
frontend/front_rps/rps_loading.html
frontend/front_rps/rps_main.css
frontend/front_rps/rps_main.html
frontend/front_rps/rps_result.css
frontend/front_rps/rps_result.html
frontend/front_rps/rps_result.js
frontend/front_rps/rps_tutorial.css
frontend/front_rps/rps_tutorial.html

- 버튼 중 클릭될 수 있는 상태인 경우 마우스 hover할 때 커서 변경
- 뒤로가기 버튼 onclick 수정
- 서버 url에 포트번호 삭제
- title을 MMG로 수정
- 결과 연결 방법 수정
- resolved: #114
<br>
-  netlify에서는 TOP 버튼이 보이지 않는데 이유는 모르겠음.
<br>

feat/fix: 가위바위보 hover, 뒤로가기, url 수정

---

frontend/front_twenty/twenty_guess.html
frontend/front_twenty/twenty_guess.js

- 애니메이션과 스무고개 알고리즘 수정
<br>
-기존에 애니메이션이 작동하면서 이후 질문이 먼저 보이는 문제를 수정
<br>

feat:애니메이션 수정 성공

---

frontend/front_rps/rps_result.js

- 가위바위보 대체 이미지 연결 수정
<br>
- rps_result.js 변경
<br>

fix: 가위바위보 대체 이미지 연결 수정

---

frontend/front_twenty/twenty_guess.js
frontend/front_twenty/twenty_main.js
frontend/front_twenty/twenty_result.js

- cosole.log 삭제
<br>
- 기능적인 부분으로는 없습니다
<br>
- 수고하셨어요!

chore:데모데이 버전 주석삭제

---

backend/src/main/resources/application.yml

- request 파일 최대 용량 수정
- resolved: #147 
<br>
- request 파일 최대 용량 수정
<br>
- x
<br>
- x
<br>

fix: request 파일 최대 용량 수정

---

frontend/front_rps/rps_input.css
frontend/front_rps/rps_input.html
frontend/front_rps/rps_loading.css
frontend/front_rps/rps_loading.html
frontend/front_rps/rps_main.css
frontend/front_rps/rps_main.html
frontend/front_rps/rps_result.css
frontend/front_rps/rps_result.html
frontend/front_rps/rps_tutorial.css
frontend/front_rps/rps_tutorial.html

- 가위바위보 수치 단위 수정
- resolved: #150
<br>
- rem으로 수치 단위를 변경해서 확대축소가 가능함
<br>
- x
<br>
- x

fix: 가위바위보 수치 단위 수정

---

README.md

- 깃허브 리드미 작성
- resolved: #153 
<br>
- 리드미 작성
<br>
- x
<br>
- x
<br>

chore: 프로젝트 설명을 위한 README.md 파일 작성
